name: Build LaTeX Document

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX files
        uses: xu-cheng/latex-action@v3
        with:
          compiler: latexmk # Can also use xelatex, lualatex, or latexmk
          args: "-interaction=nonstopmode -pdf"
          texlive_version: 2024
          root_file: |
            docs/submission2/submission2.tex
            docs/submission3/submission3.tex
            docs/DemoEqualityContribution/DemoEqualityContribution.tex
            docs/DraftDesignDoc/DraftDesignDoc.tex

      - name: Upload PDFs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdfs
          path: |
            docs/submission2/submission2.pdf
            docs/submission3/submission3.pdf
            docs/DemoEqualityContribution/DemoEqualityContribution.pdf
            docs/DraftDesignDoc/DraftDesignDoc.pdf

