name: Build LaTeX Document

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_pdfs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dir: docs/DemoEqualityContribution
            file: DemoEqualityContribution.tex
            pdf: DemoEqualityContribution.pdf
          - dir: docs/DraftDesignDoc
            file: DraftDesignDoc.tex
            pdf: DraftDesignDoc.pdf
          - dir: docs/submission2
            file: submission2.tex
            pdf: submission2.pdf
          - dir: docs/submission3
            file: submission3.tex
            pdf: submission3.pdf
          - dir: docs/DemoScript
            file: DemoScript.tex
            pdf: DemoScript.pdf

    name: Build ${{ matrix.file }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX - ${{ matrix.file }}
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ matrix.file }}
          compiler: latexmk
          args: "-interaction=nonstopmode -pdf"
          texlive_version: 2024
          working_directory: ${{ matrix.dir }}

      - name: Upload PDF - ${{ matrix.file }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.pdf }}-pdf
          path: ${{ matrix.dir }}/${{ matrix.pdf }}

