name: Build LaTeX Document

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LaTeX
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-latex-extra

      - name: Detect and compile main LaTeX file
        run: |
          # Loop over all directories in docs and compile any LaTeX files
          find docs -type f -name "*.tex" | while read main_file; do
            # Check if the file has a \documentclass (main LaTeX file)
            if grep -q '^\\documentclass' "$main_file"; then
              echo "Main LaTeX file detected: $main_file"

              # Extract directory and move there to compile
              main_dir=$(dirname "$main_file")
              cd "$main_dir" || exit 1

              # Create build directory if it doesn't exist
              mkdir -p build

              # Compile the LaTeX document twice for references
              # Use -output-directory to specify where the PDF and auxiliary files should go
              pdflatex -interaction=nonstopmode -output-directory=build "$(basename "$main_file")"
              pdflatex -interaction=nonstopmode -output-directory=build "$(basename "$main_file")"
            fi
          done

      - name: Upload PDF as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: docs/**/build/*.pdf
